[package]
authors = ["Brian Chin <brian.chin@gmail.com>"]
edition = "2021"
name = "bongo"
version = "0.1.0"

[dependencies]
thiserror = "1.0"
anyhow = "1.0.18"
unicode-segmentation = "^1.2.1"
derivative = "2.1.1"
im = "15.0.0"
dot = "0.1.4"
pretty = "0.10.0"
log = "0.4.11"
