[package]
authors = ["Brian Chin <brian.chin@gmail.com>"]
edition = "2018"
name = "bongo"
version = "0.1.0"
[dependencies]
snafu = "0.6.2"
unicode-segmentation = "^1.2.1"

[dependencies.codefmt]
path = "../codefmt"
